//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется TestUi.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MATRIX_COMPUTE              103
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_TestUiTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDC_BT_RESET_MODEL              1000
#define IDC_POS_X                       1001
#define IDC_SLIDER2                     1002
#define IDC_POS_Y                       1002
#define IDC_SLIDER3                     1003
#define IDC_POS_Z                       1003
#define IDC_POS_X2                      1004
#define IDC_MV_PITCH                    1004
#define IDC_SLIDER4                     1005
#define IDC_MV_HEADING                  1005
#define IDC_SLIDER5                     1006
#define IDC_BT_RESET_MODEL2             1007
#define IDC_POS_X3                      1008
#define IDC_MPOS_X                      1008
#define IDC_SLIDER6                     1009
#define IDC_MPOS_Y                      1009
#define IDC_SLIDER7                     1010
#define IDC_MPOS_Z                      1010
#define IDC_POS_X4                      1011
#define IDC_MM_PITCH                    1011
#define IDC_SLIDER8                     1012
#define IDC_MM_HEADING                  1012
#define IDC_SLIDER9                     1013
#define IDC_MM_ROLL                     1013
#define IDC_BT_RESET_MODEL3             1014
#define IDC_DISP_POS_X                  1014
#define IDC_DISP_POS_Y                  1015
#define IDC_DISP_POS_Z                  1016
#define IDC_MDISP_POS_X                 1017
#define IDC_MDISP_POS_Y                 1018
#define IDC_MDISP_POS_Z                 1019
#define IDC_M_V_0                       1020
#define IDC_M_V_1                       1021
#define IDC_M_V_2                       1022
#define IDC_M_V_3                       1023
#define IDC_M_V_4                       1024
#define IDC_M_V_5                       1025
#define IDC_M_V_6                       1026
#define IDC_M_V_7                       1027
#define IDC_M_V_8                       1028
#define IDC_M_V_9                       1029
#define IDC_M_V_10                      1030
#define IDC_M_V_11                      1031
#define IDC_M_V_12                      1032
#define IDC_M_V_13                      1033
#define IDC_M_V_14                      1034
#define IDC_M_V_15                      1035
#define IDC_MV_ROLL                     1036
#define IDC_MVDISPLAY_ROT_PITCH         1037
#define IDC_MVDISPLAY_ROT_HEADING       1038
#define IDC_MVDISPLAY_ROT_ROLL          1039
#define IDC_MVDISPLAY_MMROT_PITCH       1040
#define IDC_MVDISPLAY_MMROT_HEADING     1041
#define IDC_MVDISPLAY_MMROT_ROLL        1042
#define IDC_M_M_0                       1043
#define IDC_M_M_1                       1044
#define IDC_M_M_2                       1045
#define IDC_M_M_3                       1046
#define IDC_M_M_4                       1047
#define IDC_M_M_5                       1048
#define IDC_M_M_6                       1049
#define IDC_M_M_7                       1050
#define IDC_M_M_8                       1051
#define IDC_M_M_9                       1052
#define IDC_M_M_10                      1053
#define IDC_M_M_11                      1054
#define IDC_M_M_12                      1055
#define IDC_M_M_13                      1056
#define IDC_M_M_14                      1057
#define IDC_M_M_15                      1058
#define IDC_M_VM_0                      1059
#define IDC_M_VM_1                      1060
#define IDC_M_VM_2                      1061
#define IDC_M_VM_3                      1062
#define IDC_M_VM_4                      1063
#define IDC_M_VM_5                      1064
#define IDC_M_VM_6                      1065
#define IDC_M_VM_7                      1066
#define IDC_M_VM_8                      1067
#define IDC_M_VM_9                      1068
#define IDC_M_VM_10                     1069
#define IDC_M_VM_11                     1070
#define IDC_M_VM_12                     1071
#define IDC_M_VM_13                     1072
#define IDC_M_VM_14                     1073
#define IDC_M_VM_15                     1074
#define ID_VIEW_DLGBAR                  32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
